# Generated by Django 4.1.4 on 2023-02-21 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asus', '0002_pmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmodel',
            name='pimage',
            field=models.ImageField(upload_to='Asus/static'),
        ),
    ]
