# Generated by Django 4.1.4 on 2023-02-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asus', '0003_alter_pmodel_pimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='rmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pname', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('pdescription', models.CharField(max_length=100)),
                ('pimage', models.ImageField(upload_to='Asus/static')),
            ],
        ),
        migrations.CreateModel(
            name='tmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pname', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('pdescription', models.CharField(max_length=100)),
                ('pimage', models.ImageField(upload_to='Asus/static')),
            ],
        ),
        migrations.CreateModel(
            name='vmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pname', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('pdescription', models.CharField(max_length=100)),
                ('pimage', models.ImageField(upload_to='Asus/static')),
            ],
        ),
        migrations.CreateModel(
            name='zmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('pname', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
                ('pdescription', models.CharField(max_length=100)),
                ('pimage', models.ImageField(upload_to='Asus/static')),
            ],
        ),
    ]
