# Generated by Django 4.1.4 on 2023-02-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asus', '0004_rmodel_tmodel_vmodel_zmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmodel',
            name='pdescription',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='pmodel',
            name='pname',
            field=models.CharField(max_length=100),
        ),
    ]
