# Generated by Django 4.1.4 on 2023-02-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asus', '0008_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='mymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('myname', models.CharField(max_length=500)),
                ('myid', models.IntegerField()),
                ('mydate', models.DateField()),
            ],
        ),
    ]
