# Generated by Django 4.1.4 on 2023-02-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asus', '0009_mymodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='uid',
        ),
    ]
