# Generated by Django 4.1.4 on 2023-02-26 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asus', '0010_remove_mymodel_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('cartname', models.CharField(max_length=20)),
                ('cartprice', models.IntegerField()),
                ('cartdescription', models.CharField(max_length=50)),
                ('cartimage', models.ImageField(upload_to='Asus/static/cart')),
            ],
        ),
    ]
