# Generated by Django 4.1.4 on 2023-02-27 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asus', '0011_cartmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='uid',
            field=models.CharField(max_length=30),
        ),
    ]
