# Generated by Django 4.1.4 on 2023-02-27 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Asus', '0012_alter_cartmodel_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartmodel',
            name='uid',
            field=models.IntegerField(),
        ),
    ]
